server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-practice
    username: user
    password: mysecretpassword
  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    default-property-inclusion: non_null